# Generated by Django 6.0.6 on 2026-06-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operationtype',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
    ]
