# Generated by Django 6.0.6 on 2026-06-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_alter_category_options_alter_operationtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=12),
            preserve_default=False,
        ),
    ]
